
services:
  nginx:
    image: nginx:1.27.1-alpine
    container_name: nginx_proxy
    restart: always
    ports:
      - "${NGINX_HTTP_PORT:-8080}:80"
      - "${NGINX_HTTPS_PORT:-8433}:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro # Use this if HTTPS is required
    depends_on:
      - climsoft_pwa
      - climsoft_api
    networks:
      - climsoft_network

  climsoft_pwa:
    image: patowiz/climsoft-pwa
    container_name: climsoft-pwa
    restart: always
    environment:
      API_BASE_URL: ${API_BASE_URL:-http://localhost:8080/api}
    ports:
      - "4200:80"
    depends_on:
      - climsoft_api
    networks:
      - climsoft_network

  climsoft_api:
    image: patowiz/climsoft-api
    container_name: climsoft-api
    restart: always
    environment:
      DB_HOST: climsoft_db
      DB_USERNAME: ${DB_USERNAME:-my_user}
      DB_PASSWORD: ${DB_PASSWORD:-my_password}
      DB_PORT: 5432      
      DB_NAME: ${DB_NAME:-climsoft}
      WEB_APP_ALLOWED_ORIGINS: ${WEB_APP_ALLOWED_ORIGINS:-http://localhost:8080}
      SESSION_SECRET: ${SESSION_SECRET:-climsoft_secret}
    ports:
      - "3000:3000"
    depends_on:
      - climsoft_db
    networks:
      - climsoft_network

  climsoft_db:
    image: postgis/postgis:17-3.4
    container_name: climsoft-db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-climsoft}
      POSTGRES_USER: ${POSTGRES_USER:-my_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-my_password} 
    ports:
      - "5432:5432"
    volumes:
      - climsoft_data:/var/lib/postgresql/data
    networks:
      - climsoft_network

volumes:
  climsoft_data:

networks:
  climsoft_network: