
services:
  climsoft_test_db:
    image: postgis/postgis:17-3.4
    environment:
      POSTGRES_DB: climsoft
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD:-my_password} 
    ports:
      - "5432:5432"
    volumes:
      - climsoft_dev_data:/var/lib/postgresql/data
      - ./pg_exports:/var/lib/postgresql/exports  # Mount host directory

volumes:
  climsoft_dev_data: