
services:
  climsoft_test_db:
    image: postgres:16.4
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-climsoft}
      POSTGRES_USER: ${POSTGRES_USER:-my_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-my_password} 
    ports:
      - "5432:5432"
    volumes:
      - climsoft_test_data:/var/lib/postgresql/data

volumes:
  climsoft_test_data: