
services:
  db:
    image: postgres:16.2
    environment:
      POSTGRES_DB: climsoft
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password 
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: