
services:
  climsoft_pwa:
    build:
      context: ./front-end/pwa
      dockerfile: Dockerfile
    container_name: climsoft-pwa
    restart: always
    ports:
      - "4200:80"
    depends_on:
      - climsoft_api
    networks:
      - climsoft_network

  climsoft_api:
    build:
      context: ./back-end/api
      dockerfile: Dockerfile
    container_name: climsoft-api
    restart: always
    environment:
      DB_HOST: climsoft_db
      DB_USERNAME: ${DB_USERNAME:-my_user}
      DB_PASSWORD: ${DB_PASSWORD:-my_password}
      DB_PORT: 5432      
      DB_NAME: ${DB_NAME:-climsoft}
    ports:
      - "3000:3000"
    depends_on:
      - climsoft_db
    networks:
      - climsoft_network

  climsoft_db:
    image: postgres:16.4
    container_name: climsoft-db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-climsoft}
      POSTGRES_USER: ${POSTGRES_USER:-my_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-my_password} 
    ports:
      - "5432:5432"
    volumes:
      - climsoft_data:/var/lib/postgresql/data
    networks:
      - climsoft_network

volumes:
  climsoft_data:

networks:
  climsoft_network: