
services:
  climsoft_nginx_proxy:
    image: climsoftdevelopers/climsoft-nginx-proxy:5.0.0_alpha_1
    container_name: climsoft-nginx-proxy
    restart: always
    ports: # Expose to external network
      - "${HOST_HTTP_PORT}:80"
    depends_on:
      - climsoft_pwa
      - climsoft_api
    networks:
      - climsoft_network

  climsoft_pwa:
    image: climsoftdevelopers/climsoft-pwa:5.0.0_alpha_1
    container_name: climsoft-pwa
    restart: always
    environment:
      HOST_IP_ADDRESS: "${HOST_IP_ADDRESS}" # used in config.json.
      HOST_HTTP_PORT: "${HOST_HTTP_PORT}" # used in config.json.
    expose: 
      - 80 # Expose to internal network only.
    depends_on:
      - climsoft_api
    networks:
      - climsoft_network

  climsoft_api:
    image: climsoftdevelopers/climsoft-api
    container_name: climsoft-api:5.0.0_alpha_1
    restart: always
    environment:
      DB_HOST: climsoft_db
      DB_PORT: 5432
      DB_NAME: climsoft
      DB_USERNAME: postgres
      DB_PASSWORD: "${DB_PASSWORD}"
      V4_SAVE: "${V4_SAVE}"
      V4_DB_PORT: "${V4_DB_PORT}"
      V4_DB_NAME: "${V4_DB_NAME}"
      V4_DB_USERNAME: "${V4_DB_USERNAME}"
      V4_DB_PASSWORD: "${V4_DB_PASSWORD}"
      V4_DB_UTCOFFSET: "${V4_DB_UTCOFFSET}"
    expose: 
      - 3000 # Expose to internal network only. Communication to the API can go through the nginx reverse proxy.
    depends_on:
      - climsoft_db
    volumes:
      - climsoft_exports:/app/exports
    networks:
      - climsoft_network

  climsoft_db:
    image: postgis/postgis:17-3.5
    container_name: climsoft-db
    restart: always
    environment:
      POSTGRES_DB: climsoft # Default database postgres will create, required when setting up postgres the first time.
      POSTGRES_USER: postgres # Uses the default postgres username for simplicity, required when setting up postgres the first time.
      POSTGRES_PASSWORD: ${DB_PASSWORD} # Super user password, required when setting up postgres the first time.
    ports: 
      - "5432:5432" # Expose to both external and internal network.
    volumes:
      - climsoft_database:/var/lib/postgresql/data
      - climsoft_exports:/var/lib/postgresql/exports
    networks:
      - climsoft_network

volumes:
  climsoft_database:
  climsoft_exports:

networks:
  climsoft_network: